### ISSUE TITLE
Dynamically load archives

### ISSUE THREAD

**Issue by upintheairsheep** [TheTechRobo/youtubevideofinder#66]
Make the system faster by loading each item separately so if one has a tough time loading the rest show.

**Comment by TheTechRobo** [comment]
I'm assuming you mean have it show the results for each individual scraper the moment it's done rather than waiting for all of them? The trouble is, that would use up more of the server's threads at once, unless the API response is streamed or something like that (which would be tricky to implement.)

This would make #33 easy to implement.

**Comment by TheTechRobo** [comment]
Hmm, I'm thinking of something like this in the API code for streaming the API response:

```
for result in YouTubeService.run(id):
    yield result.json()
```

That would certainly work. Streaming in Flask is a lot easier than I thought.

**Comment by TheTechRobo** [comment]
There is now internal support for this (d2fffc5a69944e51744c3e2a81106b75bc58c744). However, I'm not sure how best to fit this in with the API versioning code. Currently there is a `coerce_to_version` function to coerce the API version: that would not work with a generator. I guess maybe if streaming was used it could be a generator itself that automatically downgrades the generator's results?
