### ISSUE TITLE
I wanted to share my new improved layout design to you if you don't mind.

### ISSUE THREAD

**Issue by KaineRecycler** [TheTechRobo/youtubevideofinder#82]
Hey thetechrobo I just wanted to let you know that recently I was working on my new improved future layout and design for your website
So far it's now completed and I don't know what to say about it but if you don't mind I would like to share my new improved layout
Design that I had been working on for a past few months and before I can start sharing it with you via through GitHub that
I have placed it in a ZIP file for the new improved layout and so far it's not that far from after my customized version for your website that you have that would make your YouTube website more accessible and more reliable than to your previous design that you have
But here you go made and customized built from myself and add in new improved features for your website to your YouTube video finder.
[YouTube-Content-Archive-master.zip](https://github.com/TheTechRobo/youtubevideofinder/files/14733147/YouTube-Content-Archive-master.zip)

**Comment by TheTechRobo** [comment]
Firstly, is all you did add files that say things you want added - no code changes? It would have been much easier for both of us if you just put the requests here.

Secondly, these are all major requests and I don't have the time nor the scale to implement them. I currently pay $12.45/month for my cloud services, and I'd honestly rather pay less. A search engine would not work. (You or someone else is welcome to fork it and run it on your own infrastructure, though - I encourage that!) Check out Filmot if you want a full-text search. However, it doesn't catch every video and it only provides metadata. (Useful if you don't have the video ID already, though.)

Downloading an entire channel at once is probably not happening because so many channels have hundreds or even thousands of videos. That being said, I've been wanting to write a script that can at least get you its video IDs, but I haven't gotten around to it.

Finally, if a download is available, there is a link provided next to the corresponding service. A download button would just be worse because you wouldn't be able to pick which service you want it from or even know which it is coming from. If no link is provided next to the service, then there would be nothing to put in the download button, so I'm not sure what the perceived benefit is here.
